site_name: Chat History Manager
repo_url: https://github.com/paulkiley/chat_history_manager
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
nav:
  - Overview: index.md
  - Usage:
    - Quickstart: usage.md
    - Configuration: configuration.md
    - CLI: cli.md
    - Kubernetes: kubernetes.md
  - Architecture: architecture.md
  - Development: development.md
  - ADRs:
    - 0001: adr/0001-adopt-12-factor-config-and-secrets-chain.md
    - 0002: adr/0002-chat-storage-format-and-index.md
    - 0003: adr/0003-cli-surface-and-vscode-tasks.md
    - 0004: adr/0004-testing-and-tooling-strategy.md
    - 0005: adr/0005-commit-policy-and-ci-guardrails.md
    - 0006: adr/0006-introduce-retention-policies.md
  - Community:
    - Governance: governance.md
    - Security: security.md
    - Code of Conduct: code_of_conduct.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
