name: adr-validators

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  adr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run ADR validator
        run: |
          python scripts/validate_adrs.py

