name: commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened, ready_for_review]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commits with Conventional Commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs

  comment-on-fail:
    runs-on: ubuntu-latest
    needs: lint-commits
    if: failure() && github.event_name == 'pull_request'
    steps:
      - name: Post guidance comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;
            const body = `🚦 Commit message linting failed for this PR.\n\n` +
              `Please ensure commits follow Conventional Commits.\n\n` +
              `Quick tips:\n` +
              `- Use types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert\n` +
              `- Format: type(scope?): subject (imperative, <= 50 chars)\n` +
              `- Example: feat(config): add \${VAR:-default} interpolation\n\n` +
              `Local helpers:\n` +
              `- pre-commit install --hook-type commit-msg\n` +
              `- cz commit  # guided conventional commit\n\n` +
              `To fix history, interactively rebase and edit messages:\n` +
              `- git rebase -i origin/main\n` +
              `- Mark lines as \`reword\` to edit, then force-push your branch.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body,
            });
