name: docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # pin: v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # pin: v5
        with:
          python-version: '3.12'
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-macros-plugin
      - name: Install graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz
      - name: Generate decision registry and graph
        run: |
          python scripts/generate_decision_registry.py
          dot -Tpng docs/adr/graph.dot -o docs/adr/graph.png
      - name: Build
        run: |
          mkdocs build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4a2e02b36f31d8974a0d09d3bb9f3172aa2d0d0d # pin: v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
