name: docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install mkdocs
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-macros-plugin
      - name: Install graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz
      - name: Generate decision registry and graph
        run: |
          python scripts/generate_decision_registry.py
          dot -Tpng docs/adr/graph.dot -o docs/adr/graph.png
      - name: Build
        run: |
          mkdocs build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
