name: link-check

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # pin: v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@885c65f3dc543b57c898c8099f4e08c8afd178a2 # pin: v2
        with:
          args: --no-progress --exclude "^https://img\.shields\.io" --verbose .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
