name: pin-enforcer
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  enforce-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Fail if any workflow uses unpinned actions
        run: |
          set -e
          tmp=$(mktemp)
          if grep -REn "uses:\s+[^@]+@" .github/workflows | grep -Ev "@[0-9a-fA-F]{40} " | tee "$tmp" | grep -q .; then
            echo "Unpinned GitHub Actions detected:" >&2
            cat "$tmp" >&2
            exit 1
          fi
          echo "All actions pinned to commit SHAs."
