name: pin-enforcer
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  enforce-pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Fail if any workflow uses unpinned actions
        run: |
          python - << "PY"
          import re, glob, sys
          sha = re.compile(r"@[0-9a-fA-F]{40}\b")
          bad = []
          for f in glob.glob(".github/workflows/*.yml"):
              with open(f, "r", encoding="utf-8") as fh:
                  for i, line in enumerate(fh, 1):
                      if "uses:" in line:
                          v = line.split(":",1)[1].strip()
                          if "@" not in v or not sha.search(v):
                              bad.append(f"{f}:{i}: {line.strip()}")
          if bad:
              print("Unpinned GitHub Actions detected:")
              print("
".join(bad))
              sys.exit(1)
          print("All actions pinned to commit SHAs.")
          PY
