name: python-lint

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff auto-fix (format + imports)
        run: |
          ruff --version
          ruff check --fix .
          ruff format .
      - name: Ruff lint
        run: |
          ruff check --output-format=github .
      - name: Ruff format check
        run: |
          ruff format --check .
