name: security-audit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # pin: v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # pin: v5
        with:
          python-version: '3.12'
      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pip-audit
      - name: Run pip-audit
        run: pip-audit -r <(python -c "import importlib.metadata, json; print('\n'.join(dist.metadata['Name']+'=='+dist.version for dist in importlib.metadata.distributions()))") || true
