name: traceability

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate-traceability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Validate traceability
        run: |
          python scripts/validate_traceability.py
