name: validators-sast
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  bandit-validators:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.12'
      - name: Install bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit
      - name: Scan validator scripts
        run: |
          bandit -r -ll scripts/validate_*.py || (echo "Bandit findings in validator scripts" && exit 1)
